### PR TITLE
✨ feat(*): Complete Rewrite

### PR DESCRIPTION
**Pull request by lammersbjorn**
💛 This pull request is a complete rewrite of **the entire site.**

**Some notable changes:**
* ✍️ Fixes spelling mistakes
* 📂 Better file architecture 
* ➡️ Moved inline CSS to `assets/css/style.css`
* 📱 More responsiveness
* 🎨 Fully new styling
* 🔔 Better CTA buttons
* 🗑️ Removed many Bloat
* 🌍 Small QoL changes (Eg. _blank targets)

⚠️ **Changes that will *have* to be made!**
* Hosting on another host (Eg. Netlify (Free))*

\* Hosting somewhere else will have to be done, as GitHub pages does not like the way the file architecture is. Netlify provides free hosting from a GitHub repo with automatic syncing. (DM me for help with this)

🔀 **When merging this PR**
Please make sure to Squash & Merge, this will make the commits way cleaner.

(Use the following Squash message)
`✨ feat(*): Complete Rewrite (See PR)`

### CODE REVIEW

**Comment by lammersbjorn** [comment]
image
image
image
image
image

**Comment by Pbaodoge** [comment]
Very epic redesign

**Comment by sys-256** [comment]
Thanks for your pull request, but I cannot see why we would need Netlify to host this content, as all content is fully static, and the files are named index.html and placed in subdirectories. The only reason I could see is to have the content in /public and avoid have a LICENSE file hosted, but we could create a simple GitHub Actions workflow to fix that by copying the content in /public to the gh-pages branch.

**Comment by lammersbjorn** [comment]
GitHub Pages does not allow /public. Netlify is faster. GitHub does not like the way my CSS is structured.

**Pull request merged**
